# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.CharField(blank=True, choices=[('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Гърди', 'Гърди'), ('Гръб', 'Гръб'), ('Корем', 'Корем'), ('Рамо', 'Рамо')], max_length=7, null=True, verbose_name='Категория')),
                ('equipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Оборудване')),
                ('exercise_picture', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Снимка на упражнението')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата за изпълнение')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Изпълнено упражнение',
                'verbose_name_plural': 'Изпълнени упражнения',
            },
        ),
    ]
