# Generated by Django 5.2 on 2025-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Силова тренировка', 'СИЛОВА'), ('Кардио', 'КАРДИО'), ('Стречинг', 'СТРЕЧИНГ'), ('Йога', 'ЙОГА'), ('Функционална тренировка', 'ФУНКЦИОНАЛНА'), ('Друго', 'ДРУГО')], max_length=23, null=True)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
