# Generated by Django 5.2 on 2025-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('Силова тренировка', 'Силова тренировка'), ('Кардио', 'Кардио'), ('Стречинг', 'Стречинг'), ('Йога', 'Йога'), ('Функционална тренировка', 'Функционална тренировка'), ('Друго', 'Друго')], max_length=23, null=True),
        ),
    ]
