# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexercise',
            name='workout_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutexercise', verbose_name='Упражнение'),
        ),
        migrations.AlterUniqueTogether(
            name='completedexercise',
            unique_together={('client', 'workout_exercise', 'date')},
        ),
    ]
