# Generated by Django 5.2 on 2025-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Гърди', 'Гърди'), ('Гръб', 'Гръб'), ('Корем', 'Корем'), ('Рамо', 'Рамо')], max_length=7, null=True),
        ),
    ]
