# Generated by Django 5.2 on 2025-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
