# Generated by Django 5.2 on 2025-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_exercise_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
