# Generated by Django 5.2 on 2025-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
