# Generated by Django 5.2 on 2025-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exercise_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='slug',
        ),
    ]
