# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_chest_and_more'),
        ('exercises', '0008_completedexercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedexercise',
            options={'verbose_name': 'Изпълнено упражнение', 'verbose_name_plural': 'Изпълнени упражнения'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Изпълнено на'),
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Упражниие'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Гърди', 'Гърди'), ('Гръб', 'Гръб'), ('Корем', 'Корем'), ('Рамо', 'Рамо')], max_length=7, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оборудване'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Снимка на упражнението'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Име'),
        ),
    ]
