# Generated by Django 5.2 on 2025-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_alter_completedexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име'),
        ),
    ]
