# Generated by Django 5.2 on 2025-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos', verbose_name='Снимка на упражнението'),
        ),
    ]
