# Generated by Django 5.2 on 2025-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_exercise_exercise_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Снимка на упражнението'),
        ),
    ]
