# Generated by Django 5.2 on 2025-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_alter_exercise_exercise_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexercise',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата за изпълнение'),
        ),
    ]
