# Generated by Django 5.2 on 2025-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_chest_remove_client_height_and_more'),
        ('exercises', '0013_completedexercise_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedexercise',
            unique_together={('client', 'exercise', 'date')},
        ),
    ]
