# Generated by Django 5.2 on 2025-06-15 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_alter_completedexercise_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedexercise',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата за изпълнение'),
        ),
    ]
