# Generated by Django 5.2 on 2025-06-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_alter_completedexercise_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedexercise',
            unique_together=set(),
        ),
    ]
