# Generated by Django 5.2 on 2025-06-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_alter_completedexercise_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexercise',
            name='completed_at',
        ),
    ]
