# Generated by Django 5.2 on 2025-06-15 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_chest_remove_client_height_and_more'),
        ('exercises', '0018_remove_completedexercise_completed_at'),
        ('workouts', '0003_alter_workout_options_alter_workoutexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedexercise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='completedexercise',
            name='workout',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout', verbose_name='Тренировка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата за изпълнение'),
        ),
        migrations.AlterField(
            model_name='completedexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Упражнение'),
        ),
        migrations.AlterUniqueTogether(
            name='completedexercise',
            unique_together={('client', 'exercise', 'workout', 'date')},
        ),
    ]
