# Generated by Django 5.2 on 2025-06-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_alter_completedexercise_unique_together_and_more'),
        ('workouts', '0003_alter_workout_options_alter_workoutexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedexercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout', verbose_name='Тренировка'),
        ),
    ]
