# Generated by Django 5.2 on 2025-05-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(blank=True, choices=[('Отслабване', 'ОТСЛАБВАНЕ'), ('Мускулна маса', 'МУСКУЛНА_МАСА'), ('Здравословно хранене', 'ЗДРАВОСЛОВНО_ХРАНЕНЕ'), ('Поддържане на тегло', 'ПОДДЪРЖАНЕ_НА_ТЕГЛО')], max_length=20, null=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
