# Generated by Django 5.2 on 2025-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
