# Generated by Django 5.2 on 2025-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Гръдна обиколка', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Височина', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Талия', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Тегло', max_digits=5, null=True),
        ),
    ]
