# Generated by Django 5.2 on 2025-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_appreview_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='goals',
            field=models.CharField(blank=True, choices=[('Отслабване', 'Отслабване'), ('Покачване на мускулна маса', 'Покачване на мускулна маса'), ('Стягане и тонизиране', 'Стягане и тонизиране'), ('Подобряване на издръжливостта', 'Подобряване на издръжливостта'), ('Повишаване на сила', 'Повишаване на сила'), ('Поддържане на тегло', 'Поддържане на тегло')], max_length=29, null=True, verbose_name='Цел'),
        ),
    ]
