# Generated by Django 5.2 on 2025-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
