# Generated by Django 5.2 on 2025-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_trainerrequest'),
        ('trainers', '0002_alter_trainer_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='trainerrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved', False)), fields=('client',), name='unique_pending_request_per_client'),
        ),
    ]
