# Generated by Django 5.2 on 2025-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_hip'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='neck',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Врат', max_digits=5, null=True),
        ),
    ]
