# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_neck'),
        ('trainers', '0003_alter_trainer_options_alter_trainer_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенти'},
        ),
        migrations.AlterField(
            model_name='client',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Гръдна обиколка', max_digits=5, null=True, verbose_name='Гръдна обиколка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='goals',
            field=models.CharField(blank=True, choices=[('Отслабване', 'Отслабване'), ('Мускулна маса', 'Мускулна маса'), ('Здравословно хранене', 'Здравословно хранене'), ('Поддържане на тегло', 'Поддържане на тегло')], max_length=20, null=True, verbose_name='Цел'),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Височина', max_digits=5, null=True, verbose_name='Височина'),
        ),
        migrations.AlterField(
            model_name='client',
            name='hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ханш(см)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='neck',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Врат', max_digits=5, null=True, verbose_name='Врат(см)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer', verbose_name='Треньор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Талия', max_digits=5, null=True, verbose_name='Талия(см)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Тегло', max_digits=5, null=True, verbose_name='Тегло'),
        ),
    ]
