# Generated by Django 5.2 on 2025-06-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_appreview_trainerreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='client',
            name='height',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='client',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='client',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='client',
            name='weight',
        ),
    ]
