services:
  web:
    build: .
    command: gunicorn fitness_app.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  static_volume: