# Generated by Django 5.2 on 2025-06-15 19:54

import django.core.validators
import fitness_app.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на раждане'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Създаден на'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fitness_app.accounts.models.validate_only_alphabetical], verbose_name='Първо име'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='gender',
            field=models.CharField(choices=[('Мъж', 'Мъж'), ('Жена', 'Жена'), ('Друго', 'Друго')], max_length=5, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fitness_app.accounts.models.validate_only_alphabetical], verbose_name='Фамилно име'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Профилна снимка'),
        ),
    ]
