# Generated by Django 5.2 on 2025-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fitnessuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos', verbose_name='Профилна снимка'),
        ),
    ]
