# Generated by Django 5.2 on 2025-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fitnessuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Профилна снимка'),
        ),
    ]
