# Generated by Django 5.2 on 2025-06-15 19:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('Силова тренировка', 'Силова тренировка'), ('Аеробика', 'Аеробика'), ('Йога', 'Йога'), ('Кросфит', 'Кросфит'), ('Друго', 'Друго')], max_length=17, verbose_name='Специалност')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Години опит')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Сертификати')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Био')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Телефонен номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Треньор',
                'verbose_name_plural': 'Треньори',
            },
        ),
    ]
