# Generated by Django 5.2 on 2025-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(choices=[('Силова тренировка', 'Силова тренировка'), ('Аеробика', 'Аеробика'), ('Йога', 'Йога'), ('Кросфит', 'Кросфит'), ('Друго', 'Друго')], max_length=17),
        ),
    ]
