# Generated by Django 5.2 on 2025-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(choices=[('Силов треньор', 'Силов треньор'), ('Функционален треньор', 'Функционален треньор'), ('Аеробика инструктор', 'Аеробика инструктор'), ('Кардио инструктор', 'Кардио инструктор'), ('Йога инструктор', 'Йога инструктор'), ('Пилатес инструктор', 'Пилатес инструктор'), ('Кросфит треньор', 'Кросфит треньор')], max_length=20, verbose_name='Специалност'),
        ),
    ]
