# Generated by Django 5.2 on 2025-06-09 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainer_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Треньор', 'verbose_name_plural': 'Треньори'},
        ),
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификати'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Телефонен номер'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(choices=[('Силова тренировка', 'Силова тренировка'), ('Аеробика', 'Аеробика'), ('Йога', 'Йога'), ('Кросфит', 'Кросфит'), ('Друго', 'Друго')], max_length=17, verbose_name='Специалност'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='years_of_experience',
            field=models.PositiveIntegerField(verbose_name='Години опит'),
        ),
    ]
