# Generated by Django 5.2 on 2025-06-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_options_alter_trainer_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='rating',
        ),
    ]
