# Generated by Django 5.2 on 2025-05-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0007_remove_exercise_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Гърди', 'Гърди'), ('Гръб', 'Гръб'), ('Рамо', 'Рамо')], max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('rest_time', models.PositiveIntegerField(blank=True, help_text='Почивка в секунди между сериите', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
    ]
