# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=30, verbose_name='Име')),
                ('category', models.CharField(choices=[('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Гърди', 'Гърди'), ('Гръб', 'Гръб'), ('Рамо', 'Рамо')], max_length=7, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(verbose_name='Серии')),
                ('repetitions', models.PositiveIntegerField(verbose_name='Повторения')),
                ('rest_time', models.PositiveIntegerField(blank=True, help_text='Почивка в секунди между сериите', null=True, verbose_name='Почивка между сериите')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Упражнение в тренировка',
                'verbose_name_plural': 'Упражнения в тренировка',
            },
        ),
    ]
