# Generated by Django 5.2 on 2025-05-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_remove_exercise_slug'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='series',
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('rest_time', models.PositiveIntegerField(blank=True, help_text='Почивка в секунди между сериите', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
        ),
    ]
