# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_alter_completedexercise_options_and_more'),
        ('workouts', '0002_remove_workout_exercise_remove_workout_repetitions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'verbose_name': 'Упражнение в тренировка', 'verbose_name_plural': 'Упражнения в тренировка'},
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Гърди', 'Гърди'), ('Гръб', 'Гръб'), ('Рамо', 'Рамо')], max_length=7, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='program_name',
            field=models.CharField(max_length=30, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Упражнение'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='repetitions',
            field=models.PositiveIntegerField(verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest_time',
            field=models.PositiveIntegerField(blank=True, help_text='Почивка в секунди между сериите', null=True, verbose_name='Почивка между сериите'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='series',
            field=models.PositiveIntegerField(verbose_name='Серии'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout', verbose_name='Тренировка'),
        ),
    ]
