# Generated by Django 5.2 on 2025-05-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('Закуска', 'ЗАКУСКА'), ('Обяд', 'ОБЯД'), ('Вечеря', 'ВЕЧЕРЯ'), ('Снакс / междинно хранене', 'СНАКС')], max_length=24)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField()),
                ('carbohydrate', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('proteins', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_plans.nutritionplan')),
            ],
        ),
    ]
