# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('nutrition_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Име')),
                ('calories_per_100g', models.FloatField(blank=True, null=True, verbose_name='Калории на 100 грама')),
                ('carbohydrates_per_100g', models.FloatField(blank=True, null=True, verbose_name='Въглехидрати на 100 грама')),
                ('fats_per_100g', models.FloatField(blank=True, null=True, verbose_name='Мазнини на 100 грама')),
                ('proteins_per_100g', models.FloatField(blank=True, null=True, verbose_name='Протеини на 100 грама')),
                ('serving_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер на порция')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('Закуска', 'Закуска'), ('Обяд', 'Обяд'), ('Вечеря', 'Вечеря'), ('Снакс / междинно хранене', 'Снакс / междинно хранене')], max_length=24, verbose_name='Тип хранене')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории')),
                ('carbohydrate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Въглехидрати')),
                ('fats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мазнини')),
                ('proteins', models.PositiveIntegerField(blank=True, null=True, verbose_name='Протеини')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition_plans.nutritionplan', verbose_name='Хранителен план')),
            ],
            options={
                'verbose_name': 'Хранене',
                'verbose_name_plural': 'Хранения',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Количество в грамове', verbose_name='Количество в грамове')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='meals.meal', verbose_name='Хранене')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Хранителен продукт',
                'verbose_name_plural': 'Хранителни продукти',
            },
        ),
    ]
