# Generated by Django 5.2 on 2025-05-22 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100g', models.FloatField()),
                ('carbohydrates_per_100g', models.FloatField()),
                ('fats_per_100g', models.FloatField()),
                ('proteins_per_100g', models.FloatField()),
                ('serving_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Количество в грамове')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='meals.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.product')),
            ],
        ),
    ]
