# Generated by Django 5.2 on 2025-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_product_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
