# Generated by Django 5.2 on 2025-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_product_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='day_of_week',
            field=models.CharField(choices=[('Понеделник', 'Понеделник'), ('Вторник', 'Вторник'), ('Сряда', 'Сряда'), ('Четвъртък', 'Четвъртък'), ('Петък', 'Петък'), ('Събота', 'Събота'), ('Неделя', 'Неделя')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
