# Generated by Django 5.2 on 2025-05-27 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_day_of_week'),
        ('nutrition_plans', '0002_alter_nutritionplan_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition_plans.nutritionplan'),
        ),
    ]
