# Generated by Django 5.2 on 2025-06-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_neck'),
        ('meals', '0006_remove_meal_day_of_week_meal_date_alter_meal_plan'),
        ('nutrition_plans', '0002_alter_nutritionplan_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition_plans.nutritionplan'),
        ),
    ]
