# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_chest_and_more'),
        ('meals', '0007_meal_client_alter_meal_plan'),
        ('nutrition_plans', '0003_alter_nutritionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'Хранителен продукт', 'verbose_name_plural': 'Хранителни продукти'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Хранене', 'verbose_name_plural': 'Хранения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='meals.meal', verbose_name='Хранене'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.FloatField(help_text='Количество в грамове', verbose_name='Количество в грамове'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrate',
            field=models.PositiveIntegerField(verbose_name='Въглехидрати'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.PositiveIntegerField(verbose_name='Мазнини'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('Закуска', 'Закуска'), ('Обяд', 'Обяд'), ('Вечеря', 'Вечеря'), ('Снакс / междинно хранене', 'Снакс / междинно хранене')], max_length=24, verbose_name='Тип хранене'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition_plans.nutritionplan', verbose_name='Хранителен план'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins',
            field=models.PositiveIntegerField(verbose_name='Протеини'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories_per_100g',
            field=models.FloatField(blank=True, null=True, verbose_name='Калории на 100 грама'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_per_100g',
            field=models.FloatField(blank=True, null=True, verbose_name='Въглехидрати на 100 грама'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats_per_100g',
            field=models.FloatField(blank=True, null=True, verbose_name='Мазнини на 100 грама'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins_per_100g',
            field=models.FloatField(blank=True, null=True, verbose_name='Протеини на 100 грама'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serving_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер на порция'),
        ),
    ]
