# Generated by Django 5.2 on 2025-06-10 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_alter_fooditem_options_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Въглехидрати'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мазнини'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Протеини'),
        ),
    ]
