# Generated by Django 5.2 on 2025-05-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_client_neck'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Понеделник'), ('Tue', 'Вторник'), ('Wed', 'Сряда'), ('Thu', 'Четвъртък'), ('Fri', 'Петък'), ('Sat', 'Събота'), ('Sun', 'Неделя')], max_length=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
    ]
