# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Упражнение в програмата',
                'verbose_name_plural': 'Упражнения в програмата',
            },
        ),
    ]
