# Generated by Django 5.2 on 2025-06-05 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programexercise',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='programexercise',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
