# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_chest_and_more'),
        ('program_exercises', '0002_remove_programexercise_day_of_week_and_more'),
        ('workouts', '0003_alter_workout_options_alter_workoutexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programexercise',
            options={'verbose_name': 'Упражнение в програмата', 'verbose_name_plural': 'Упражнения в програмата'},
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout', verbose_name='Тренировка'),
        ),
    ]
