# Generated by Django 5.2 on 2025-06-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_alter_completedexercise_workout'),
        ('program_exercises', '0003_alter_programexercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='exercise',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Упражнение'),
            preserve_default=False,
        ),
    ]
