# Generated by Django 5.2 on 2025-06-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_exercises', '0004_programexercise_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programexercise',
            name='exercise',
        ),
    ]
