# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тегло (кг)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Височина (см)')),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Врат (см)')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Гръдна обиколка (см)')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Талия (см)')),
                ('hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ханш (см)')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мускулна маса (%)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Подкожни мазнини (%)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Прогрес',
                'verbose_name_plural': 'Прогреси',
            },
        ),
    ]
