# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_chest_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Прогрес', 'verbose_name_plural': 'Прогреси'},
        ),
        migrations.AlterField(
            model_name='progress',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Подкожни мазнини'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мускулна маса'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тегло'),
        ),
    ]
