# Generated by Django 5.2 on 2025-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_progress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Гръдна обиколка (см)'),
        ),
        migrations.AddField(
            model_name='progress',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Височина (см)'),
        ),
        migrations.AddField(
            model_name='progress',
            name='hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ханш (см)'),
        ),
        migrations.AddField(
            model_name='progress',
            name='neck',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Врат (см)'),
        ),
        migrations.AddField(
            model_name='progress',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Талия (см)'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Подкожни мазнини (%)'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мускулна маса (%)'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тегло (кг)'),
        ),
    ]
