# Generated by Django 5.2 on 2025-06-15 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progress_chest_progress_height_progress_hip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
