# Generated by Django 5.2 on 2025-06-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Име на хр. плана')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('calories', models.PositiveIntegerField(verbose_name='Калории')),
                ('carbohydrate', models.PositiveIntegerField(verbose_name='Въглехидрати')),
                ('fats', models.PositiveIntegerField(verbose_name='Мазнини')),
                ('proteins', models.PositiveIntegerField(verbose_name='Протеини')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Хранителен план',
                'verbose_name_plural': 'Хранителни планове',
            },
        ),
    ]
