# Generated by Django 5.2 on 2025-05-27 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_neck'),
        ('nutrition_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='clients.client'),
        ),
    ]
