# Generated by Django 5.2 on 2025-06-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_chest_and_more'),
        ('nutrition_plans', '0002_alter_nutritionplan_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionplan',
            options={'verbose_name': 'Хранителен план', 'verbose_name_plural': 'Хранителни планове'},
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='carbohydrate',
            field=models.PositiveIntegerField(verbose_name='Въглехидрати'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='fats',
            field=models.PositiveIntegerField(verbose_name='Мазнини'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Име на хр. плана'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='proteins',
            field=models.PositiveIntegerField(verbose_name='Протеини'),
        ),
    ]
